# Generated by Django 3.0.2 on 2020-12-17 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=20)),
                ('Country', models.CharField(blank=True, max_length=20)),
                ('Image', models.ImageField(blank=True, upload_to='images/user/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
