# Generated by Django 3.0.2 on 2020-11-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Keywords', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('Status', models.CharField(max_length=10)),
                ('Slug', models.SlugField()),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Category')),
            ],
        ),
    ]
