# Generated by Django 3.0.2 on 2020-11-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201103_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
    ]
