# Generated by Django 3.0.2 on 2020-11-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
    ]
