# Generated by Django 3.0.2 on 2020-11-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201103_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Keywords', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
                ('Price', models.FloatField()),
                ('Amount', models.IntegerField()),
                ('MinAmount', models.IntegerField()),
                ('Details', models.TextField(max_length=255)),
                ('Slug', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
