# Generated by Django 3.0.2 on 2020-12-04 17:16

import ckeditor_uploader.fields
from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
