# Generated by Django 3.0.2 on 2020-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201204_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Parent',
            new_name='parent',
        ),
    ]
