# Generated by Django 3.0.2 on 2020-12-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201205_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
