# Generated by Django 3.0.2 on 2020-12-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201221_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
