# Generated by Django 3.0.2 on 2020-12-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_delete_orderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
