# Generated by Django 3.0.2 on 2020-12-21 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_auto_20201221_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adminnote',
            new_name='Adminnote',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='Create_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ip',
            new_name='Ip',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='update_at',
            new_name='Update_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='User',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Amount', models.FloatField()),
                ('Status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=10)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
