# Generated by Django 3.0.2 on 2020-12-02 15:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Keywords', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=50)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Phone', models.CharField(blank=True, max_length=15)),
                ('Fax', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Smtpserver', models.CharField(blank=True, max_length=50)),
                ('Smtpmail', models.CharField(blank=True, max_length=50)),
                ('Smtpport', models.CharField(blank=True, max_length=15)),
                ('Icon', models.ImageField(blank=True, upload_to='images/')),
                ('Facebook', models.CharField(blank=True, max_length=100)),
                ('Instagram', models.CharField(blank=True, max_length=100)),
                ('Twitter', models.CharField(blank=True, max_length=100)),
                ('Youtube', models.CharField(blank=True, max_length=100)),
                ('Aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('Contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('References', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('Status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
