# Generated by Django 3.0.2 on 2020-12-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
