# Generated by Django 3.0.2 on 2021-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordernumber', models.IntegerField()),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.TextField()),
                ('Status', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=10)),
                ('Create_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
