# Generated by Django 3.0.2 on 2021-04-27 11:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
